name: test & build master

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v5
        with:
          name: unit-coverage
          path: coverage/
          retention-days: 7

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: lint
    environment: integration
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload E2E test coverage
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: e2e-coverage
          path: coverage/
          retention-days: 7

  status-comment:
    name: Comment PR Status
    runs-on: ubuntu-latest
    needs: [lint, unit-test, e2e-test]
    if: always()
    permissions:
      pull-requests: write
    steps:
      - name: Download unit test coverage
        uses: actions/download-artifact@v5
        with:
          name: unit-coverage
          path: coverage-unit/

      - name: Download E2E test coverage
        uses: actions/download-artifact@v5
        with:
          name: e2e-coverage
          path: coverage-e2e/
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const lintResult = '${{ needs.lint.result }}';
            const unitTestResult = '${{ needs.unit-test.result }}';
            const e2eTestResult = '${{ needs.e2e-test.result }}';

            const statusEmoji = (result) => {
              if (result === 'success') return '✅';
              if (result === 'failure') return '❌';
              return '⚠️';
            };

            const overall = lintResult === 'success' && unitTestResult === 'success' && e2eTestResult === 'success'
              ? '✅ All checks passed!'
              : '❌ Some checks failed';

            const comment = `## CI Status Report

            ${overall}

            | Job | Status |
            |-----|--------|
            | Lint | ${statusEmoji(lintResult)} ${lintResult} |
            | Unit Tests | ${statusEmoji(unitTestResult)} ${unitTestResult} |
            | E2E Tests | ${statusEmoji(e2eTestResult)} ${e2eTestResult} |

            ---
            *Triggered by commit: ${context.sha.substring(0, 7)}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
